// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC414nEY-uv-KGY08oqNdcqPK7h-BDj78I',
    appId: '1:265385003093:web:3154d9eeb3458cfeb2ecdc',
    messagingSenderId: '265385003093',
    projectId: 'music-app-102a5',
    authDomain: 'music-app-102a5.firebaseapp.com',
    storageBucket: 'music-app-102a5.appspot.com',
    measurementId: 'G-PD0LT3JE9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKcYoFV8T8Ynb4kFbY4hKjZIQ9MIup_xo',
    appId: '1:265385003093:android:adceb8285c8d2b4ab2ecdc',
    messagingSenderId: '265385003093',
    projectId: 'music-app-102a5',
    storageBucket: 'music-app-102a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu_tyhP2-t2PbbB8lLr3k3g_6ALyKmJTQ',
    appId: '1:265385003093:ios:4693b43c3f3f8b80b2ecdc',
    messagingSenderId: '265385003093',
    projectId: 'music-app-102a5',
    storageBucket: 'music-app-102a5.appspot.com',
    iosBundleId: 'com.example.datnNpq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu_tyhP2-t2PbbB8lLr3k3g_6ALyKmJTQ',
    appId: '1:265385003093:ios:db693fa466f29035b2ecdc',
    messagingSenderId: '265385003093',
    projectId: 'music-app-102a5',
    storageBucket: 'music-app-102a5.appspot.com',
    iosBundleId: 'com.example.datnNpq.RunnerTests',
  );
}
